// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD7Bqf7jVSO6r37NYPMt8I4w0KTkgqUdKc',
    appId: '1:776609377643:web:cdf064372a72b924ec702e',
    messagingSenderId: '776609377643',
    projectId: 'masjid-7afb5',
    authDomain: 'masjid-7afb5.firebaseapp.com',
    storageBucket: 'masjid-7afb5.firebasestorage.app',
    measurementId: 'G-W9S5457S6J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDMAFKecm3-bXUG-8HN023Cl6XRdMQL0zU',
    appId: '1:776609377643:android:3ac84b613846d411ec702e',
    messagingSenderId: '776609377643',
    projectId: 'masjid-7afb5',
    storageBucket: 'masjid-7afb5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDrfy2L_R-3ynUnfZwWkYN8hDGDXJ8bxtQ',
    appId: '1:776609377643:ios:907a8fee718b4d44ec702e',
    messagingSenderId: '776609377643',
    projectId: 'masjid-7afb5',
    storageBucket: 'masjid-7afb5.firebasestorage.app',
    iosBundleId: 'com.example.masjidapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDrfy2L_R-3ynUnfZwWkYN8hDGDXJ8bxtQ',
    appId: '1:776609377643:ios:907a8fee718b4d44ec702e',
    messagingSenderId: '776609377643',
    projectId: 'masjid-7afb5',
    storageBucket: 'masjid-7afb5.firebasestorage.app',
    iosBundleId: 'com.example.masjidapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD7Bqf7jVSO6r37NYPMt8I4w0KTkgqUdKc',
    appId: '1:776609377643:web:9d8af2b9cd2face4ec702e',
    messagingSenderId: '776609377643',
    projectId: 'masjid-7afb5',
    authDomain: 'masjid-7afb5.firebaseapp.com',
    storageBucket: 'masjid-7afb5.firebasestorage.app',
    measurementId: 'G-2SMEEJ3SPH',
  );
}
